/**
 * Golden-vector suite: prove the SDK's EIP-712 signing reproduces the exact
 * digests computed by the real on-chain SignatureHelpers library.
 *
 * Vectors come from veranta-tx-builder/tests/golden-vectors/vectors.json
 * (generated by executing the compiled contracts on anvil), shared verbatim
 * with the Python SDK. If these pass, the signer handles every quirk:
 * millisecond deadlines, mixed `_`-prefix field names, the deadline-less
 * TpSlReq with a negative int256, and the DelegateReq ToS constant.
 */

import { recoverAddress } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { describe, expect, it } from "vitest";
import { DigestMismatchError } from "../src/errors.js";
import { signIntent } from "../src/signing/intents.js";
import { INTENT_TYPES } from "../src/signing/schema.js";
import { toSigner } from "../src/signing/signer.js";
import type { IntentPayload } from "../src/types.js";
import VECTORS from "./vectors/vectors.json";

// well-known anvil test key — test-only
const TEST_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" as const;
const TEST_ADDRESS = privateKeyToAccount(TEST_KEY).address;

interface Vector {
  kind: string;
  message: Record<string, unknown>;
  digest: `0x${string}`;
  structHash?: string;
}

const vectors = (VECTORS as any).vectors as Vector[];

function payloadFor(vector: Vector): IntentPayload {
  const kind = vector.kind;
  return {
    intent: kind,
    signerRule: kind === "DelegateReq" ? "trader-only" : "trader-or-delegate",
    domain: (VECTORS as any).domain,
    primaryType: kind,
    types: INTENT_TYPES[kind]!,
    message: vector.message as Record<string, any>,
    digest: vector.digest,
    encodedIntent: "0x",
  };
}

describe("golden vectors", () => {
  it.each(vectors.map((v) => [v.kind, v] as const))(
    "digest matches on-chain library: %s",
    async (_kind, vector) => {
      const signer = toSigner(TEST_KEY);
      const signed = await signIntent(payloadFor(vector), signer);

      // signature is 65-byte r||s||v and recovers to the signer
      expect(signed.signature).toMatch(/^0x[0-9a-f]{130}$/i);
      const v = Number.parseInt(signed.signature.slice(130, 132), 16);
      expect([27, 28]).toContain(v);
      const recovered = await recoverAddress({ hash: vector.digest, signature: signed.signature });
      expect(recovered.toLowerCase()).toBe(TEST_ADDRESS.toLowerCase());
    },
  );

  it("digest mismatch is fatal", async () => {
    const payload = payloadFor(vectors[0]!);
    payload.digest = `0x${"00".repeat(32)}`;
    await expect(signIntent(payload, toSigner(TEST_KEY))).rejects.toBeInstanceOf(
      DigestMismatchError,
    );
  });

  it("all 17 intent kinds covered", () => {
    const kinds = new Set(vectors.map((v) => v.kind));
    expect(kinds).toEqual(new Set(Object.keys(INTENT_TYPES)));
    expect(kinds.size).toBe(17);
  });
});
